### PR TITLE
Add support for Art Blocks in the Royalty Registry override functionality

### PR DESCRIPTION
**Pull request by jakerockland**
In the future, we would like to follow this up by adding support to the Royalty Registry for interfacing directly with the `getRoyaltyData` method on the Art Blocks smart contract, but, IIUC, I believe making this change is a simpler more immediate term solution to allow for adding override support to set the a royalty % for the Art Blocks contract tokens across the board within the Royalty Registry.

### CODE REVIEW

**Comment by jakerockland** [comment]
cc @snowfro

**Comment by wwhchung** [comment]
This works.  Change looks good.  Am going to merge it into a separate branch and pull it all together with a pending Nifty Gateway change.  Rolling out to testnets and polygon first would be quicker.  Would that be helpful to you?

**Comment by wwhchung** [comment]
If you want to make a change to the RoyaltyEngineV1 as well, can wait to queue that up as well.  Just let me know.

A few of the other folks in the group have reviewed the Registry changes already and gave it a thumbsup

**Comment by ryley-o** [comment]
Hi @wwhchung! 👋  I'm a newer member of the ArtBlocks eng team. 

Just wanted to note that this PR currently does not pass all tests, working on updates to fix. 

Also, yes, we do want to add support for Art Blocks to the RoyaltEngineV1. Would you prefer that be included in this PR, or separate? (might be a timing consideration for you)

**Comment by wwhchung** [comment]
Thanks.  A separate PR for the engine would be great.

**Comment by ryley-o** [comment]
@wwhchung Cc @jakerockland 
This is ready to go.

Override logic added in RoyaltyRegistry.sol, added permissions tests: all are passing.

Note that IArtBlocks a little quirky due to use of public variable `address public admin` in Art Blocks contract. Interfaces don't support public variables, so instead the public variable's getter function was added to the `IArtBlocks` interface. Recommend double-checking that permissions work appropriately when deployed on testnet.

Will break out a separate PR for engine changes.

**Comment by wwhchung** [comment]
Can I request that you split out the test artblocks deployer to a separate deployer and update truffle-config.js to simply start with more than 10 accounts (like 20)? It’s a more comprehensive test strategy

**Review by jakerockland — COMMENTED** [review]
This LGTM. @wwhchung's suggestions SGTM as well if you're willing to make the update @ryley-o 🙏

**Comment by ryley-o** [comment]
@wwhchung the test artblocks deployer is now a separate deployer. Enabling >10 accounts during testing means running ganache-cli manually with `-a 15` to get 15 accounts, for example. Thus, the readme was updated to reflect the two commands now required to run tests. 🙂

**Review by wwhchung — APPROVED** [review]
LGTM

**Pull request merged**
