### PR TITLE
Add test run command to package.json and clarify docs

### PR DESCRIPTION
**Pull request by jakerockland**
This makes it a bit clearer to external contributors how to get started with navigating this repo. I think its also worth considering _not_ checking in the package-lock.json file, but that is a team preference thing and I don't have a strong opinion here on suggesting a preference to the Manifold team, just wanted to flag this :)

Happy to reword/rearrange the piece added to the README here however the Manifold team sees fit, no strong opinions here on where this lives–just wanted to streamline a bit the information for future travelers.

Cheers 💜

### CODE REVIEW

**Comment by jakerockland** [comment]
cc @ryley-o @wwhchung

**Comment by wwhchung** [comment]
Thanks!  Good changes except I still think node_modules should be excluded.  Checking in package-lock.json so people can recreate the exact build.

Any reason why we should include node_modules?

**Comment by wwhchung** [comment]
ignore my previous comment.  I misread the changelist.  Changes look good! ❤️

**Review by wwhchung — CHANGES_REQUESTED** [review]
truffle should be a devDependency instead of a regulary dependency right?

**Comment by jakerockland** [comment]
Yep yep, I think `node_modules` was a false-flag as a diff just given a newline being added for `./open-zepplin`. Good call re: dev dependency for truffle 👍 😄 PR updated!

**Review by wwhchung — APPROVED** [review]

**Comment by wwhchung** [comment]
@jakerockland @ryley-o I've deployed to rinkeby, mumbai, polygon.  Ropsten later tonight.  Mainnet soon.  Are you able to test and make sure your overrides work on rinkeby?

**Comment by ryley-o** [comment]
Great! I will take a look today to confirm things work as expected on rinkeby

**Comment by ryley-o** [comment]
@wwhchung can you point me to the deployed contracts on rinkeby? thanks!

**Comment by wwhchung** [comment]
royaltyregistry.xyz :)

**Comment by ryley-o** [comment]
@wwhchung Cc @jakerockland 
Tested `setRoyaltyLookupAddress` on rinkeby and was successful. This LGTM!
ref tx: https://rinkeby.etherscan.io/tx/0x80cb2b5679912d172a0cb13b24510f84a954855c8c6fabfa21862a05fb2a0b63#eventlog

>Note: royaltyAddress was set to a nonsensical contract in this test tx. I will play with override contracts separately :smile:

**Comment by wwhchung** [comment]
It's now on mainnet! :)

**Pull request merged**
