### PR TITLE
RoyaltyEngine support of new multi-contract override interface (Art Blocks)

### PR DESCRIPTION
**Pull request by ryley-o**
## Overview
A multi-contract royalty override interface is proposed to be supported by the RoyaltyEngine. The interface generalizes a request for royalties to `n` recipients, given `tokenAddress` and `tokenId`. Because override contracts are new (not legacy), requiring the new multi-contract overrides to call out support of the new interface per ERC-165 is included. This enables efficient checks in the RoyaltyEngine, avoiding adding another try/catch pattern.

The multi-contract override architecture integrates well with existing Art Blocks contracts. Thus, mock Art Blocks Override contracts are included and added to tests.

Cc @jakerockland

### CODE REVIEW

**Comment by wwhchung** [comment]
Doesn't this interface already exist with IManifold and IRaribleV1?  Why define a new interface when you can just adopt the existing ones?  Is this new interface being used already?

**Comment by wwhchung** [comment]
Also, the reason we don't do the ERC165 check is because it's cheaper to just try and catch the failure. :)

**Comment by wwhchung** [comment]
In fact, since the function signature looks to be identical to IManifold's getRoyalties, I think everything works without your changes, doesn't it?

**Comment by ryley-o** [comment]
> In fact, since the function signature looks to be identical to IManifold's getRoyalties, I think everything works without your changes, doesn't it?

IManifold uses `function getRoyalties(uint256 tokenId)`, and the multi-contract override uses `function getRoyalties(address tokenAddress, uint256 tokenId)` (in `contracts/overrides/IMultiContractRoyaltyOverride`)

**Comment by ryley-o** [comment]
> we don't do the ERC165 check is because it's cheaper to just try and catch

fair enough, I can remove it if that is preferred :slight:

**Comment by wwhchung** [comment]
Ah yes, you're correct.  But I don't really understand the purpose, as isn't this just duplicating what the royalty registry is doing and chaining yet another lookup location?  Are you able to elaborate on why there needs to be another intermediate storage location for royalty lookups?

There may be a better way if I could see the underlying live implementation.  Also, maybe we can continue this discussion on a chat platform? Please feel free to dm me on twitter.

**Comment by ryley-o** [comment]
After some discussion about alternate architectures, closing this PR. 

>Note: someone may find this branch useful in the future if they have an even stronger use-case for a legacy, multi-contract override

**Pull request closed without merging**
